name = "worldbuilding"
main = "src/index.js"
compatibility_date = "2026-09-11"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "worldbuilding-db"
database_id = "cb899d0d-5cd8-4937-9a4a-2d16e58ec5f8"
